# Generated by Django 3.1.7 on 2023-11-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
